### ISSUE TITLE
Only looks for labels starting with needs/blocked

### ISSUE THREAD

**Issue by spilth** [mkenyon/colored-labels-for-pivotal-tracker#2]
We have fancy X's in our labels for things like `blocked` and `needs`.  It might be nice if it looked for that text anywhere in the labels, rather than just the beginning of the label.

**Comment by michaelabon** [comment]
@spilth Those kinds of labels were the inspiration for this extension. If you really want to draw attention to `blocked` and `needs` labels, then you should install this extension.

However, not everyone on the team runs the extension.

Additionally, some teams use a low-ASCII value starting character to trick Tracker's lexicographical label sorting. They'll still want to use those characters.

Thanks for the issue!
