### ISSUE TITLE
Red labels should be red in the detail view too

### ISSUE THREAD

**Issue by michaelabon** [mkenyon/colored-labels-for-pivotal-tracker#5]
Shouldn't this be red? That'd be awesome! I want to make this happen.

![2015-08-11_2346](https://cloud.githubusercontent.com/assets/567950/9216197/40a92122-4083-11e5-9c2f-a8b6c0ae3fc4.png)

**Comment by cjcjameson** [comment]
Can we bump this to "bug"? We have the following issue: when we look at a label in the detail view (that has "blocked" in it), the label is not highlighted with any color at all, and it cannot be deleted / selected, etc.

![screen shot 2015-08-24 at 10 32 49 am](https://cloud.githubusercontent.com/assets/6885889/9447306/7ee8fc38-4a4b-11e5-8213-e5fb4ebf7f82.png)

![screen shot 2015-08-24 at 10 31 34 am](https://cloud.githubusercontent.com/assets/6885889/9447277/5bd7cd3c-4a4b-11e5-9dc4-9d4695b10393.png)

**Comment by mkenyon** [comment]
Whoa! That's a good find. I'll investigate it!

**Comment by cjcjameson** [comment]
Yea, and if you want to kick it over to the Beach, I'm sure there's folks
up in SF who might have bandwidth.

On Mon, Aug 24, 2015 at 10:38 AM, Mike Kenyon <notifications@github.com>
wrote:

> Whoa! That's a good find. I'll investigate it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mkenyon/red-labels-for-pivotal-tracker/issues/5#issuecomment-134312147>
> .
>



-- 
C.J. Jameson
Pivotal Labs
