### ISSUE TITLE
Blocked label in detail view is not highlighted and cannot be interacted with

### ISSUE THREAD

**Issue by michaelabon** [mkenyon/colored-labels-for-pivotal-tracker#6]
Thanks to @cjcjameson for reporting:

> We have the following issue: when we look at a label in the detail view (that has "blocked" in it), the label is not highlighted with any color at all, and it cannot be deleted / selected, etc.

Extracted from #5.

![screen shot 2015-08-24 at 10 32 49 am](https://cloud.githubusercontent.com/assets/6885889/9447306/7ee8fc38-4a4b-11e5-8213-e5fb4ebf7f82.png)

![screen shot 2015-08-24 at 10 31 34 am](https://cloud.githubusercontent.com/assets/6885889/9447277/5bd7cd3c-4a4b-11e5-9dc4-9d4695b10393.png)

**Comment by cjcjameson** [comment]
Thanks!!
